### ISSUE TITLE
Datatable paging issues when sorting by column

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#656] opened 2022-07-29 03:18 UTC
Go to a datagrid, then sort by a column that has a lot of values that are the same, have tested that the following show the error:

Classifications grid - allele origin
Annotation pipeline runs - error status

If you then page through the grid after sorting by column, sometimes you will see the same rows appear again.

From memory we had the same issue with JQGrid, and solved it by always specifying the PK as a secondary sort by column so it was consistently ordered

**Comment by TheMadBug** [comment] 2022-07-29 03:35
We should be able to implement this in
```
class DatatableConfig(Generic[DC]):
     def ordering(self, qs: QuerySet) -> QuerySet[DC]:
```
just injecting "pk" at the end of the sort_by_list (with the direction based on the sort_string.

If a RichColumn is assigned a value for default_sort, then no matter the sort order, this will always be used at the end.
So in the case of ClassificationColumns, created has default_sort.
In Shariant you wouldn't find two classifications made within the same millisecond, but if you restored data from a dump I could see it happening.

AnnotationRunColumns does NOT have a default sort, but could be given one on the ID column just like VariantAnnotationVersionColumns has. Though obviously code directly in DatatableConfig could fix it in all instances (possibly only if a default sort is not provided).

**Comment by davmlaw** [comment] 2022-08-01 01:07
@TheMadBug is there supposed to be a break in the self.rich_columns loop (last loop) in  ```DatatableConfig,ordering```?

**Comment by TheMadBug** [comment] 2022-08-01 01:11
Uh yeah, I don't think that break is meant to be in there at all actually. If multiple columns mark themselves as default_sort then they should both be used.

**Comment by davmlaw** [comment] 2022-08-12 04:52
**Shariant test:** - I don't know if we were able to recreate this in Shariant - but test sorting eg classification grid by columns and paging through making sure sort works w/o duplicates

**Comment by EmmaTudini** [comment] 2022-08-15 03:46
@TheMadBug @davmlaw Would this affect the activity page? Cause I have noticed that the same record at the bottom of a page is the same as the top record of the next page?

**Comment by TheMadBug** [comment] 2022-08-15 03:51
Activity page isn't a Datatable, it's using my own custom code because it mixes classification changes and flag activity.
Just tested it then and confirmed it's an issue for the activity page.

The problem with the activity page is rather than working on a page number, the URL works on a timestamp, so that something like
https://shariant.org.au/classification/activity?latest_timestamp=1660346489.513864
always shows the same records.

If actions are done in a transaction there could be a chance that two things happen at exactly the same timestamp, so if I try to avoid duplicating the bottom record at the top of the next one, there's a very small chance I'll miss something.

That said, I could check the database to see if this ever realistically happens (things happening at the same millisecond) and if not I could fix it so the last item of one page isn't always the first item of the next.

**Comment by EmmaTudini** [comment] 2022-09-06 01:04
Testing:
- Logged in to Shariant test as non-admin assigned to VCGS Test (emmatudini@gmail.com)
- Searched for TTN
- Went to three pages (automatically went to pages of 50) 
- Also sorted by clinical significance and lab

Expected output: Shouldn't be any duplicates across pages

Actual output: Passed
Note: Also tested on BRCA1 (changed number of records per page to 10). Normal and sorted on last curated - Passed

- Went to classifications listing

**Closed** 2022-09-08 06:38 UTC
