### ISSUE TITLE
No warning when reference base different than genome reference

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#176] opened 2021-01-08 06:26 UTC
Related to #150 and #151. 

Made up an impossible variant (7:151902477 C>A) and entered it via variant >  enter variants (GRCh37).
Variant created: http://144.6.229.160/variantopedia/view_variant/258664069 
Variant appears to be 'annotated', no warning that variant can't exist. 

See test case: https://app.qase.io/run/VG/dashboard/28

**Comment by davmlaw** [comment] 2021-01-08 06:34
Can you define "nonsensical variant that can't exist/map to the human genome" please?

**Comment by sksmi** [comment] 2021-01-08 06:37
As in the variant above can't exist because the ref at 7:151902477 is G for GRCh37.

**Comment by davmlaw** [comment] 2021-01-08 06:52
OK so by "impossible/nonsensical" you mean "different than the genome fasta patch version on the server"

There are now 7 issues tagged with "Reference base" that are all basically the same issue....

The reference bases change with genome build patch versions and we can't enforce that everyone uses the same patch version, eg need to accept HGVS from other versions for Shariant and from old VCF people upload to VariantGrid.

I can't remember if the other issues suggested raising a warning, but that seems like a good idea, and pretty easy to do (as opposed to properly fix the issue and deal with all the different patch versions)

**Comment by sksmi** [comment] 2021-01-08 07:29
7 down with one warning, sounds like a winner. Also throws responsibility to end user to decide how to interpret which is ideal on both ends - esp. that for most coding regions it's more likely that this is a user error/typo.

**Comment by davmlaw** [comment] 2021-01-12 04:16
Duplicate of #68 - Warn when variant ref doesn't match our reference fasta

**Closed by davmlaw** 2021-01-12 04:16 UTC
Labels: Reference base
