### ISSUE TITLE
HPO gene matching returns fewer genes than expected

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#97] opened 2020-10-23 06:52 UTC
**Describe the bug**
HPO gene matching returns fewer genes than expected. Suspect this may be due to outdated annotations. 

**To Reproduce**
1. Go to https://variantgrid.com/patients/view_patient/1312
2. Click on genes tab. See 5 genes matching HP:0004808
3.  Go to https://hpo.jax.org/app/browse/term/HP:0004808
4. See 62 genes matching HPO. 

**Expected behavior**
Expect HPO matching to return 62 genes as per HPO database. 

**Other**
![image](https://user-images.githubusercontent.com/8601717/96965695-1e04cf80-1554-11eb-8020-f7770cb04230.png)

![image](https://user-images.githubusercontent.com/8601717/96965727-2a892800-1554-11eb-8c0e-c673220e37fd.png)

**Comment by davmlaw** [comment] 2020-10-23 07:53
Dupe of variantgrid_private #1036 - Upgrade OMIM / HPO (SA Path want for upgrade)

**Closed by davmlaw** 2020-10-23 07:53 UTC
Labels: bug, duplicate
