### ISSUE TITLE
User Feedback : Zygosity in sample node

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#353] opened 2021-05-10 05:31 UTC
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2711/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2711/)

```
User Feedback : Zygosity in sample node
```

**Comment by davmlaw** [comment] 2021-05-10 05:43
Dupe of https://github.com/SACGF/variantgrid_sapath/issues/149

**Closed by davmlaw** 2021-05-10 05:43 UTC
